### ISSUE TITLE
Error in parsing favorites after upgrading to 0.1.5

### ISSUE THREAD

**Issue by Kunibert-007** [BuZZy1337/ioBroker.doorbird#2]
After installing the new update 0.1.5 today I get every three minutes the following error in the log:

```
doorbird.0 | 2018-09-20 11:45:25.680
| error | Error in Parsing favorites: SyntaxError: Invalid regular expression: /(?<=\/\/)(.*)(?=\/)/: Invalid group
-- | -- | -- | --
```

**Comment by BuZZy1337** [comment]
Could you please do an update of the Adapter via Github?
After that, please restart the Adapter and check the Logs.. There should be a warn message that one Favorite has the Wrong URL.. Could you please show me this warn message?

![screenshot - 20 09 2018 12_17_40](https://user-images.githubusercontent.com/6979405/45812172-5085d380-bccf-11e8-9e0f-bf1a46869efa.png)
![screenshot - 20 09 2018 12_18_22](https://user-images.githubusercontent.com/6979405/45812175-5380c400-bccf-11e8-8265-204fdacaf4bc.png)

**Comment by BuZZy1337** [comment]
Is 192.168.0.32 the correct IP Address of your ioBroker Host and 8100 the correct Doorbird Adapter Port?

Which Node version is installed on your ioBroker Host?

**Comment by Kunibert-007** [comment]
I have Node-Version 6.14.4.
As IP-address I have "localhost" and the Doorbird Adapter-Port is default I think. I haven't changed it.  Now I have changed the IP-address to the real IP and now it seems to work.  Thanks!

**Comment by BuZZy1337** [comment]
Okay,..
One last question:
was "localhost" filled in automatically during the installation or did you enter that?

**Comment by Kunibert-007** [comment]
I wrote it in the field manually because in other adapters you have to fill in "localhost" instead of the ip (e. g. in the adapter "Backitup" for the MySQL-Backup). So I am not sure in which adapter you should use the ip and where is localhost the better option.
Thx for your support!

**Comment by BuZZy1337** [comment]
Okay, I will change the description of that field and add a 'is valid ip?' check for that field..
You are welcome. :relaxed:
