### ISSUE TITLE
Periodic error 400 "while setting the Motion schedule". 

### ISSUE THREAD

**Issue by Garfonso** [BuZZy1337/ioBroker.doorbird#4]
I get this error periodically and after start of the adapter:
'doorbird.0 | 2018-11-28 22:12:16.323 | error | null (Statuscode: 400)
doorbird.0 | 2018-11-28 22:12:16.322 | error | There was an Error while setting the Motion schedule.'

Not sure what that means. I have a DoorBird D2101V and everything else seems to work ok. But motion snapshots do not work, either. In the doorbird app I have motion detection disabled (cloud recording & push messages). Not sure if that is connected? I tried to enable it, but the error did stay.

**Comment by Garfonso** [comment]
Hi,

today I switched on debuging and now get a bit more logging:
`doorbird.0 | 2018-12-21 12:42:22.837 | error | null (Statuscode: 400)
doorbird.0 | 2018-12-21 12:42:22.836 | error | There was an Error while setting the Motion schedule..
doorbird.0 | 2018-12-21 12:42:22.770 | debug | We need to create a Schedule for the Motion Sensor!
doorbird.0 | 2018-12-21 12:42:22.768 | debug | Okay we dont need to create any Doorbell-Schedules..
doorbird.0 | 2018-12-21 12:42:22.768 | debug | Checking if we need to create Schedules on DoorBird Device..`

I checked in the app and there does not seem to be a schedule for motion detection there, either. Hm.

**Comment by BuZZy1337** [comment]
I am going to rewrite the whole Adapter because the Doorbird-Developerteam is not very helpful with their support regarding changes and bugs of the API. :disappointed:

**Comment by 1704eu** [comment]
I also received the error, my problem was / my solution is: I had an own HTTP API call registered. When I went into the app to see the schedule "Administration => schedule for doorbell" in the upper left corner you have to switch to "HTTP calls" there I realized, that trying to set a schedule it told me "blocked by ... (my own http call)" It seems that all HTTP calls have one schedule.  I deleted my own http call and the error is gone. And the adapter works great now.
