### ISSUE TITLE
Periodic error ECONNREFUSED 

### ISSUE THREAD

**Issue by peer69** [BuZZy1337/ioBroker.doorbird#6]
Every 24 hours (+/- 30 min) I can see the following error in the log: 

`Error in testBird() Request: Error: connect ECONNREFUSED [IP]:80`

The adapter as well as the doorbird seem to work as expected. Is this an issue with my doorbird installation or the adapter or is this even an issue at all, except for the log entry? 

I can reproduce the 24h cycle by restarting the adapter. This shifts the 24h cycle to the time of the restart.

**Comment by BuZZy1337** [comment]
No this is not an issue at all.. That is Doorbird which is doing some "work" every 24h and then refuses the connection. I will change that error handling..
